//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backuptool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7z.exe")]
        public string Path7z {
            get {
                return ((string)(this["Path7z"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10737418240")]
        public long BatchSizeMax {
            get {
                return ((long)(this["BatchSizeMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-spf -scsUTF-8 -t7z -mx=5 -mmemuse=p50")]
        public string Additional7zArgs {
            get {
                return ((string)(this["Additional7zArgs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\temp")]
        public string DestinationPath {
            get {
                return ((string)(this["DestinationPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FixLongPath {
            get {
                return ((bool)(this["FixLongPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("both")]
        public string WorkMode {
            get {
                return ((string)(this["WorkMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>\AppData</string>
  <string>C:\PerfLogs</string>
  <string>C:\Program Files</string>
  <string>C:\Program Files (x86)</string>
  <string>C:\ProgramData</string>
  <string>:\$Recycle.Bin</string>
  <string>C:\Python</string>
  <string>C:\Sandbox</string>
  <string>C:\tools</string>
  <string>C:\usr</string>
  <string>C:\Temp</string>
  <string>C:\Tmp</string>
  <string>C:\Windows</string>
  <string>C:\WSL</string>
  <string>C:\Users\Public</string>
  <string>C:\Users\Supervisor</string>
  <string>C:\Users\Администратор</string>
  <string>C:\Users\KlNagSvc</string>
  <string>hiberfil.sys</string>
  <string>pagefile.sys</string>
  <string>D:\install</string>
  <string>D:\ARM</string>
  <string>C:\CONS.CFG</string>
  <string>.lnk</string>
  <string>.url</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BlackList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BlackList"]));
            }
        }
    }
}
